site_name: My Documentation
nav:
  - Home: index.md
  - Red Eye Club: tlpi.md
  - Linux Amdinistration: linux-admin.md
  - Security: itsec.md
  - Cheat Sheet: cheat-sheet.md
  # - Garage Sale: garage-sale.md
